# -*- coding: utf-8 -*-
"""Project_NTI_(1) (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvKDD5zMq4PlneIt_9CxOL5rhNDAptxs
"""

# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import streamlit as st

import os
import zipfile

# Define the ZIP file name uploaded to Colab
zip_path = "archive (4).zip"
extract_path = "UNSW_NB15"

# Create target directory if it does not exist
os.makedirs(extract_path, exist_ok=True)

# Extract all contents from the ZIP archive
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Files extracted successfully!")

for root, dirs, files in os.walk(extract_path):
    for file in files:
        print(os.path.join(root, file))

# Load parquet files correctly from the extracted folder
train_df = pd.read_parquet(
    "UNSW_NB15/UNSW_NB15_training-set.parquet", engine="fastparquet"
)
test_df = pd.read_parquet(
    "UNSW_NB15/UNSW_NB15_testing-set.parquet", engine="fastparquet"
)

print("Train Data Loaded Successfully!")
print("Test Data Loaded Successfully!")
print("Train Shape:", train_df.shape)
print("Test Shape :", test_df.shape)

# Check Train and Test Dataset Shape

print("Train Shape:", train_df.shape)
print("Test Shape :", test_df.shape)

# Preview Train and Test Data

st.write(train_df.head())
st.write(test_df.head())

# Check Columns and Data Types

print("Dataset Columns:")
print(train_df.columns.tolist())

print("\nData Types:")
print(train_df.dtypes)

# Check Dataset Information

print("TRAIN DATA INFO")
print("=" * 50)
train_df.info()

print("\nTEST DATA INFO")
print("=" * 50)
test_df.info()

# Check Missing Values

print("Missing Values in Train:")
print(train_df.isnull().sum())

print("\nTotal Missing Values in Train:", train_df.isnull().sum().sum())

print("\nMissing Values in Test:")
print(test_df.isnull().sum())

print("\nTotal Missing Values in Test:", test_df.isnull().sum().sum())

# Check Duplicate Rows

print("Duplicate Rows in Train:", train_df.duplicated().sum())
print("Duplicate Rows in Test :", test_df.duplicated().sum())

# Check Target Class Distribution

print("Train Label Distribution:")
print(train_df["label"].value_counts())

print("\nTrain Label Percentage:")
print(train_df["label"].value_counts(normalize=True) * 100)

print("\nTest Label Distribution:")
print(test_df["label"].value_counts())

print("\nTest Label Percentage:")
print(test_df["label"].value_counts(normalize=True) * 100)

# Visualize Target Class Distribution

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.countplot(data=train_df, x="label", ax=axes[0])
axes[0].set_title("Train Label Distribution")
axes[0].set_xlabel("Label (0 = Normal, 1 = Attack)")
axes[0].set_ylabel("Count")

sns.countplot(data=test_df, x="label", ax=axes[1])
axes[1].set_title("Test Label Distribution")
axes[1].set_xlabel("Label (0 = Normal, 1 = Attack)")
axes[1].set_ylabel("Count")

plt.tight_layout()
plt.show()

# Check Attack Categories Distribution

print("Train Attack Categories:")
print(train_df["attack_cat"].value_counts())

print("\nTest Attack Categories:")
print(test_df["attack_cat"].value_counts())

# Visualize Attack Categories Distribution

plt.figure(figsize=(12, 6))

sns.countplot(
    data=train_df,
    y="attack_cat",
    order=train_df["attack_cat"].value_counts().index
)

plt.title("Train Attack Categories Distribution")
plt.xlabel("Count")
plt.ylabel("Attack Category")

plt.tight_layout()
plt.show()

# Numerical Features Statistics

train_df.describe().T

# Correlation Matrix

numeric_df = train_df.select_dtypes(include=["number"])

corr_matrix = numeric_df.corr()

plt.figure(figsize=(18, 14))
sns.heatmap(
    corr_matrix,
    cmap="coolwarm",
    center=0
)

plt.title("Correlation Matrix of Numerical Features")
plt.tight_layout()
plt.show()

# Correlation with Target Label

label_corr = corr_matrix["label"].drop("label").sort_values(ascending=False)

print("Correlation with Label:")
print(label_corr)

# Categorical Features Summary

categorical_cols = ["proto", "service", "state", "attack_cat"]

for col in categorical_cols:
    print(f"\n{col}")
    print("-" * 40)
    print("Number of unique values:", train_df[col].nunique())
    print(train_df[col].value_counts().head(15))

# Visualize Main Categorical Features

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

train_df["proto"].value_counts().head(10).plot(
    kind="bar",
    ax=axes[0]
)
axes[0].set_title("Top 10 Protocols")
axes[0].set_xlabel("Protocol")
axes[0].set_ylabel("Count")
axes[0].tick_params(axis="x", rotation=45)

train_df["service"].value_counts().plot(
    kind="bar",
    ax=axes[1]
)
axes[1].set_title("Service Distribution")
axes[1].set_xlabel("Service")
axes[1].set_ylabel("Count")
axes[1].tick_params(axis="x", rotation=45)

train_df["state"].value_counts().plot(
    kind="bar",
    ax=axes[2]
)
axes[2].set_title("State Distribution")
axes[2].set_xlabel("State")
axes[2].set_ylabel("Count")
axes[2].tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()

# Important Numerical Features Distribution

features = ["rate", "sload", "dload", "ct_src_dport_ltm", "ct_dst_sport_ltm", "dmean"]

fig, axes = plt.subplots(2, 3, figsize=(16, 9))

for feature, ax in zip(features, axes.flatten()):
    sns.histplot(
        data=train_df,
        x=feature,
        hue="label",
        bins=50,
        ax=ax,
        element="step"
    )
    ax.set_title(f"{feature} Distribution")

plt.tight_layout()
plt.show()

# EDA Summary

print("EDA SUMMARY")
print("=" * 60)

print("Train Shape:", train_df.shape)
print("Test Shape :", test_df.shape)

print("\nMissing Values:")
print("Train:", train_df.isnull().sum().sum())
print("Test :", test_df.isnull().sum().sum())

print("\nDuplicate Rows:")
print("Train:", train_df.duplicated().sum())
print("Test :", test_df.duplicated().sum())

print("\nTrain Target Distribution:")
print(train_df["label"].value_counts(normalize=True) * 100)

print("\nTest Target Distribution:")
print(test_df["label"].value_counts(normalize=True) * 100)

print("\nNumber of Attack Categories:")
print(train_df["attack_cat"].nunique())

print("\nNumber of Unique Protocols:")
print(train_df["proto"].nunique())

print("\nTop Positive Correlations with Label:")
print(label_corr.head(5))

print("\nTop Negative Correlations with Label:")
print(label_corr.tail(5))

# ==========================================
# MEMBER 2 -  DATA CLEANING


print("Before removing duplicates:")
print("Train Shape:", train_df.shape)
print("Test Shape :", test_df.shape)

# Remove duplicate rows
train_df = train_df.drop_duplicates()
test_df = test_df.drop_duplicates()

print("\nAfter removing duplicates:")
print("Train Shape:", train_df.shape)
print("Test Shape :", test_df.shape)

# Verify duplicates were removed
print("\nRemaining Duplicates:")
print("Train:", train_df.duplicated().sum())
print("Test :", test_df.duplicated().sum())

# DEFINE FEATURES AND TARGET
X_train = train_df.drop(columns=["label", "attack_cat"], errors="ignore")
y_train = train_df["label"]

X_test = test_df.drop(columns=["label", "attack_cat"], errors="ignore")
y_test = test_df["label"]

# CATEGORICAL ENCODING
from sklearn.preprocessing import OrdinalEncoder

cat_cols = ["proto", "service", "state"]

encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
X_train[cat_cols] = encoder.fit_transform(X_train[cat_cols])
X_test[cat_cols] = encoder.transform(X_test[cat_cols])

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)

# IDENTIFY FEATURE TYPES

categorical_cols = ["proto", "service", "state"]

numerical_cols = X_train.select_dtypes(
    include=["int8", "int16", "int32", "int64", "float32", "float64"]
).columns.tolist()

print("Categorical Features:")
print(categorical_cols)

print("\nNumber of Numerical Features:", len(numerical_cols))
print(numerical_cols)

# ENCODING

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_train_cat = encoder.fit_transform(X_train[categorical_cols])

X_test_cat = encoder.transform(X_test[categorical_cols])

print("Encoded Train Shape:", X_train_cat.shape)
print("Encoded Test Shape :", X_test_cat.shape)

# FEATURE SCALING
scaler = StandardScaler()

X_train_num = scaler.fit_transform(
    X_train[numerical_cols]
)

X_test_num = scaler.transform(
    X_test[numerical_cols]
)

print("Scaled Train Shape:", X_train_num.shape)
print("Scaled Test Shape :", X_test_num.shape)

# COMBINE FEATURES


X_train_processed = np.hstack(
    [X_train_num, X_train_cat]
)

X_test_processed = np.hstack(
    [X_test_num, X_test_cat]
)

print("Final X_train Shape:", X_train_processed.shape)
print("Final X_test Shape :", X_test_processed.shape)

# smote = SMOTE(random_state=42)

# X_train_resampled, y_train_resampled = smote.fit_resample(
#     X_train_processed,
#     y_train
# )

# print("Before SMOTE:")
# print(y_train.value_counts())

# print("\nAfter SMOTE:")
# print(y_train_resampled.value_counts())

# Align variable names for downstream cells
X_train_resampled = X_train
y_train_resampled = y_train
X_test_processed = X_test

# FINAL PREPROCESSING CHECK

print("FINAL DATA CHECK")
print("=" * 50)

print("\nTraining Data:")
print("X_train_resampled:", X_train_resampled.shape)
print("y_train_resampled:", y_train_resampled.shape)

print("\nTesting Data:")
print("X_test_processed:", X_test_processed.shape)
print("y_test:", y_test.shape)

print("\nClass Distribution After SMOTE:")
print(y_train_resampled.value_counts())

print("\nMissing Values in Final Arrays:")
print("Train:", np.isnan(X_train_resampled).sum())
print("Test :", np.isnan(X_test_processed).sum())

"""# MEMBER 3 - BASELINE ML MODELS

"""

# ==========================================
# IMPORT MODELS & METRICS
# ==========================================

import time

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# ==========================================
# HELPER FUNCTION - TRAIN & EVALUATE
# ==========================================

results = {}

def evaluate_model(name, model, X_train, y_train, X_test, y_test):
    """Train a model, evaluate it, and store/print its metrics."""

    start = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start

    y_pred = model.predict(X_test)

    # ROC-AUC needs probability scores (if available)
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
        roc_auc = roc_auc_score(y_test, y_proba)
    else:
        roc_auc = np.nan

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    results[name] = {
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1-Score": f1,
        "ROC-AUC": roc_auc,
        "Train Time (s)": train_time
    }

    print(f"===== {name} =====")
    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"ROC-AUC   : {roc_auc:.4f}")
    print(f"Train Time: {train_time:.2f}s")
    print("\nConfusion Matrix:")
    print(cm)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    plt.figure(figsize=(4, 3))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Normal", "Attack"],
                yticklabels=["Normal", "Attack"])
    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.tight_layout()
    plt.show()

    return model

"""## 1) Logistic Regression

"""

log_reg = LogisticRegression(max_iter=1000, random_state=42)

log_reg = evaluate_model(
    "Logistic Regression",
    log_reg,
    X_train_resampled, y_train_resampled,
    X_test_processed, y_test
)

"""## 2) K-Nearest Neighbors (KNN)

"""

knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)

knn = evaluate_model(
    "KNN",
    knn,
    X_train_resampled, y_train_resampled,
    X_test_processed, y_test
)

"""## 3) Decision Tree

"""

dt = DecisionTreeClassifier(max_depth=15, random_state=42)

dt = evaluate_model(
    "Decision Tree",
    dt,
    X_train_resampled, y_train_resampled,
    X_test_processed, y_test
)

"""## 4) Naive Bayes
**Note:** GaussianNB is used since the features are a mix of standardized numerical data and one-hot encoded categorical data (continuous-valued after preprocessing). Given the strong feature independence assumption, Naive Bayes is expected to underperform compared to the other models on this dataset — it's included here as a baseline for comparison, not as a top candidate.

"""

nb_model = GaussianNB()

nb_model = evaluate_model(
    "Naive Bayes",
    nb_model,
    X_train_resampled, y_train_resampled,
    X_test_processed, y_test
)

"""## Baseline Models Comparison

"""

# ==========================================
# COMPARE ALL BASELINE MODELS
# ==========================================

results_df = pd.DataFrame(results).T
results_df = results_df.sort_values(by="F1-Score", ascending=False)

print("BASELINE MODELS COMPARISON")
print("=" * 60)
display(results_df)

# Visualize comparison
metrics_to_plot = ["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"]

results_df[metrics_to_plot].plot(
    kind="bar",
    figsize=(12, 6)
)
plt.title("Baseline Models Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.ylim(0, 1)
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

print("\nBest Model by F1-Score:", results_df["F1-Score"].idxmax())

# Convert categorical columns to numerical
X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)

# Make sure both datasets have the same columns
X_train, X_test = X_train.align(
    X_test,
    join="left",
    axis=1,
    fill_value=0
)

"""## MEMBER 4 ADVANCED MACHINE LEARNING MODELS

### 1) Random Forest Classifier
"""

from sklearn.ensemble import RandomForestClassifier

# Create the model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train_resampled, y_train_resampled)

# Make predictions
rf_pred = rf_model.predict(X_test_processed)

# Calculate prediction probabilities
rf_prob = rf_model.predict_proba(X_test_processed)[:, 1]

"""### 2) EVALUATE RANDOM FOREST"""

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_roc_auc = roc_auc_score(y_test, rf_prob)

print("RANDOM FOREST RESULTS")
print("=" * 60)

print(f"Accuracy:  {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall:    {rf_recall:.4f}")
print(f"F1-Score:  {rf_f1:.4f}")
print(f"ROC-AUC:   {rf_roc_auc:.4f}")

# Classification Report
print("\nCLASSIFICATION REPORT")
print("=" * 60)

print(classification_report(y_test, rf_pred))

# Confusion Matrix
plt.figure(figsize=(6, 5))

sns.heatmap(
    confusion_matrix(y_test, rf_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Random Forest - Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

"""## SUPPORT VECTOR MACHINE (SVM)"""

from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler

# 1. Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test_processed)

# 2. Create LinearSVC model
svm_model = LinearSVC(max_iter=2000, random_state=42)

# 3. Train the model
svm_model.fit(X_train_scaled, y_train_resampled)

# 4. Make predictions
svm_pred = svm_model.predict(X_test_scaled)

# EVALUATE SVM

svm_accuracy = accuracy_score(y_test, svm_pred)
svm_precision = precision_score(y_test, svm_pred)
svm_recall = recall_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)

print("SVM RESULTS")
print("=" * 60)

print(f"Accuracy:  {svm_accuracy:.4f}")
print(f"Precision: {svm_precision:.4f}")
print(f"Recall:    {svm_recall:.4f}")
print(f"F1-Score:  {svm_f1:.4f}")

# Classification Report

print("\nCLASSIFICATION REPORT")
print("=" * 60)

print(classification_report(y_test, svm_pred))

# Confusion Matrix

plt.figure(figsize=(6, 5))

sns.heatmap(
    confusion_matrix(y_test, svm_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("SVM - Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

# Calculate ROC-AUC for LinearSVC

svm_score = svm_model.decision_function(X_test_scaled)

svm_roc_auc = roc_auc_score(y_test, svm_score)

print(f"ROC-AUC: {svm_roc_auc:.4f}")

# Store SVM Results

results["SVM"] = {
    "Accuracy": svm_accuracy,
    "Precision": svm_precision,
    "Recall": svm_recall,
    "F1-Score": svm_f1,
    "ROC-AUC": svm_roc_auc
}

"""##Gradient Boosting Classifier"""

from sklearn.ensemble import GradientBoostingClassifier

# Create the model
gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

# Train the model
gb_model.fit(X_train_resampled, y_train_resampled)

# Make predictions
gb_pred = gb_model.predict(X_test_processed)

# Calculate prediction probabilities
gb_prob = gb_model.predict_proba(X_test_processed)[:, 1]

# EVALUATE GRADIENT BOOSTING

gb_accuracy = accuracy_score(y_test, gb_pred)
gb_precision = precision_score(y_test, gb_pred)
gb_recall = recall_score(y_test, gb_pred)
gb_f1 = f1_score(y_test, gb_pred)
gb_roc_auc = roc_auc_score(y_test, gb_prob)

print("GRADIENT BOOSTING RESULTS")
print("=" * 60)

print(f"Accuracy:  {gb_accuracy:.4f}")
print(f"Precision: {gb_precision:.4f}")
print(f"Recall:    {gb_recall:.4f}")
print(f"F1-Score:  {gb_f1:.4f}")
print(f"ROC-AUC:   {gb_roc_auc:.4f}")

# Classification Report

print("\nCLASSIFICATION REPORT")
print("=" * 60)

print(classification_report(y_test, gb_pred))

# Confusion Matrix

plt.figure(figsize=(6, 5))

sns.heatmap(
    confusion_matrix(y_test, gb_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Gradient Boosting - Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

# Store Gradient Boosting Results

results["Gradient Boosting"] = {
    "Accuracy": gb_accuracy,
    "Precision": gb_precision,
    "Recall": gb_recall,
    "F1-Score": gb_f1,
    "ROC-AUC": gb_roc_auc
}

"""## XGBOOST CLASSIFIER"""

from xgboost import XGBClassifier

# Create the model
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    eval_metric="logloss"
)

# Train the model
xgb_model.fit(X_train_resampled, y_train_resampled)

# Make predictions
xgb_pred = xgb_model.predict(X_test_processed)

# Calculate prediction probabilities
xgb_prob = xgb_model.predict_proba(X_test_processed)[:, 1]

# EVALUATE XGBOOST

xgb_accuracy = accuracy_score(y_test, xgb_pred)
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
xgb_roc_auc = roc_auc_score(y_test, xgb_prob)

print("XGBOOST RESULTS")
print("=" * 60)

print(f"Accuracy:  {xgb_accuracy:.4f}")
print(f"Precision: {xgb_precision:.4f}")
print(f"Recall:    {xgb_recall:.4f}")
print(f"F1-Score:  {xgb_f1:.4f}")
print(f"ROC-AUC:   {xgb_roc_auc:.4f}")

# Classification Report

print("\nCLASSIFICATION REPORT")
print("=" * 60)

print(classification_report(y_test, xgb_pred))

# Confusion Matrix

plt.figure(figsize=(6, 5))

sns.heatmap(
    confusion_matrix(y_test, xgb_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("XGBoost - Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

# Store XGBoost Results

results["XGBoost"] = {
    "Accuracy": xgb_accuracy,
    "Precision": xgb_precision,
    "Recall": xgb_recall,
    "F1-Score": xgb_f1,
    "ROC-AUC": xgb_roc_auc
}

"""##Advanced Models Comparison"""

advanced_results = pd.DataFrame(results).T

print("ADVANCED MODELS COMPARISON")
print("=" * 80)

display(advanced_results)

"""###ADVANCED MODELS VISUALIZATION"""

advanced_results.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Advanced Machine Learning Models Comparison")
plt.xlabel("Models")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.legend(title="Metrics")
plt.grid(axis="y", alpha=0.3)

plt.show()

"""##Cross-Validation"""

# RANDOM FOREST CROSS-VALIDATION
from sklearn.model_selection import cross_val_score

rf_cv_scores = cross_val_score(
    rf_model,
    X_train_resampled,
    y_train_resampled,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

print("RANDOM FOREST CROSS-VALIDATION RESULTS")
print("=" * 60)
print(f"5-Fold F1-Scores: {rf_cv_scores}")
print(f"Mean F1-Score:    {rf_cv_scores.mean():.4f}")
print(f"Standard Dev:     {rf_cv_scores.std():.4f}")

# SVM CROSS-VALIDATION

svm_cv_scores = cross_val_score(
    svm_model,
    X_train_scaled,
    y_train_resampled,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

print("SVM CROSS-VALIDATION RESULTS")
print("=" * 60)
print(f"5-Fold F1-Scores: {svm_cv_scores}")
print(f"Mean F1-Score:    {svm_cv_scores.mean():.4f}")
print(f"Standard Dev:     {svm_cv_scores.std():.4f}")

# GRADIENT BOOSTING CROSS-VALIDATION

gb_cv_scores = cross_val_score(
      gb_model,
      X_train_resampled,
      y_train_resampled,
      cv=5,
      scoring='f1',
      n_jobs=-1
  )

print("GRADIENT BOOSTING CROSS-VALIDATION RESULTS")
print("=" * 60)
print(f"5-Fold F1-Scores: {gb_cv_scores}")
print(f"Mean F1-Score:    {gb_cv_scores.mean():.4f}")
print(f"Standard Dev:     {gb_cv_scores.std():.4f}")

# XGBOOST CROSS-VALIDATION

xgb_cv_scores = cross_val_score(
    xgb_model,
    X_train_resampled,
    y_train_resampled,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

print("XGBOOST CROSS-VALIDATION RESULTS")
print("=" * 60)
print(f"5-Fold F1-Scores: {xgb_cv_scores}")
print(f"Mean F1-Score:    {xgb_cv_scores.mean():.4f}")
print(f"Standard Dev:     {xgb_cv_scores.std():.4f}")

# CROSS-VALIDATION COMPARISON

cv_results = pd.DataFrame({
    "Random Forest": [rf_cv_scores.mean()],
    "SVM": [svm_cv_scores.mean()],
    "Gradient Boosting": [gb_cv_scores.mean()],
    "XGBoost": [xgb_cv_scores.mean()]
})

print("CROSS-VALIDATION MEAN F1-SCORE")
print("=" * 60)

display(cv_results)

# CROSS-VALIDATION VISUALIZATION

plt.figure(figsize=(10, 6))

plt.bar(
    cv_results.columns,
    cv_results.iloc[0]
)

plt.title("Cross-Validation Mean F1-Score Comparison")
plt.xlabel("Models")
plt.ylabel("Mean F1-Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.grid(axis="y", alpha=0.3)

plt.show()

"""## HYPERPARAMETER OPTIMIZATION"""

# GRADIENT BOOSTING HYPERPARAMETER OPTIMIZATION

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingClassifier

# Create Pipeline
gb_pipeline = Pipeline([
    ("smote", SMOTE(random_state=42)),
    ("gb", GradientBoostingClassifier(random_state=42))
])

# Define parameters for OPTIMIZATION
gb_param_dist = {
    "gb__n_estimators": [100, 150, 200, 250],
    "gb__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "gb__max_depth": [2, 3, 4, 5],
    "gb__min_samples_split": [2, 5, 10],
    "gb__min_samples_leaf": [1, 2, 4]
}

# Create RandomizedSearchCV
opt_search = RandomizedSearchCV(
    estimator=gb_pipeline,
    param_distributions=gb_param_dist,
    n_iter=2,
    scoring="f1",
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1,
)

# Train the search
opt_search.fit(X_train, y_train)

# PRINT BEST PARAMETERS AND SCORES
print("BEST GRADIENT BOOSTING PARAMETERS")
print("=" * 60)

print(opt_search.best_params_)

print("\nBEST CROSS-VALIDATION F1-SCORE:")
print(f"{opt_search.best_score_:.4f}")

"""### Optimized Gradient Boosting Evaluation"""

# Make predictions on the original test set
y_pred = opt_search.predict(X_test)

# Calculate evaluation metrics
gb_optimized_accuracy = accuracy_score(y_test, y_pred)
gb_optimized_precision = precision_score(y_test, y_pred)
gb_optimized_recall = recall_score(y_test, y_pred)
gb_optimized_f1 = f1_score(y_test, y_pred)

# Print Detailed Results
print("OPTIMIZED GRADIENT BOOSTING RESULTS")
print("=" * 60)

print(f"Accuracy:  {gb_optimized_accuracy:.4f}")
print(f"Precision: {gb_optimized_precision:.4f}")
print(f"Recall:    {gb_optimized_recall:.4f}")
print(f"F1-Score:  {gb_optimized_f1:.4f}")

print("\nCLASSIFICATION REPORT")
print("=" * 60)
print(classification_report(y_test, y_pred))

# 1. Generate predictions using the best estimator from RandomizedSearchCV
gb_optimized_pred = opt_search.best_estimator_.predict(X_test)

# 2. Print Classification Report
print("\nOPTIMIZED GRADIENT BOOSTING CLASSIFICATION REPORT")
print("=" * 60)
print(classification_report(y_test, gb_optimized_pred))

plt.figure(figsize=(6, 5))

sns.heatmap(
    confusion_matrix(y_test, gb_optimized_pred),
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Optimized Gradient Boosting - Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

"""### Before vs After Optimization Comparison"""

comparison_before_after = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-Score"],

    "Before Optimization": [
        gb_accuracy,
        gb_precision,
        gb_recall,
        gb_f1
    ],

    "After Optimization": [
        gb_optimized_accuracy,
        gb_optimized_precision,
        gb_optimized_recall,
        gb_optimized_f1
    ]
})

print("GRADIENT BOOSTING - BEFORE VS AFTER OPTIMIZATION")
print("=" * 60)

display(comparison_before_after)

# BEFORE VS AFTER OPTIMIZATION VISUALIZATION

comparison_before_after.set_index("Metric").plot(
    kind="bar",
    figsize=(10, 6)
)
[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

plt.title("Gradient Boosting - Before vs After Optimization")
plt.xlabel("Metrics")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.grid(axis="y", alpha=0.3)

plt.show()

"""MEMBER 5"""

#Final Comparison & Evaluation Table

comparison_df = pd.DataFrame(results).T

print('🏆 Model Performance Comparison Table:')
st.write(
    comparison_df.sort_values(by='F1-Score', ascending=False).style.background_gradient(
        cmap='Blues'
    )
)

plt.figure(figsize=(12, 6))
comparison_df[['Accuracy', 'Precision', 'Recall', 'F1-Score']].plot(
    kind='bar', figsize=(14, 6), colormap='Set2', edgecolor='black'
)

plt.title(
    '🔍 Comprehensive Comparison of ML Models Across Metrics',
    fontsize=16,
    fontweight='bold',
)
plt.xlabel('Models', fontsize=14)
plt.ylabel('Score', fontsize=14)
plt.xticks(rotation=30, ha='right', fontsize=12)
plt.ylim(0, 1.05)
plt.legend(loc='lower right', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

#Best model selection based on F1-Score

if results:
  best_model_df = pd.DataFrame(results).T

  best_model_name = best_model_df['F1-Score'].idxmax()
  best_f1_score = best_model_df.loc[best_model_name, 'F1-Score']
  best_accuracy = best_model_df.loc[best_model_name, 'Accuracy']

  print('=' * 50)
  print(f'🌟 THE WINNING MODEL: {best_model_name} 🌟')
  print('=' * 50)
  print(f'   - Best F1-Score : {best_f1_score:.4f}')
  print(f'   - Accuracy      : {best_accuracy:.4f}')
  print(
      '\n💡 Reason for selection: This model achieved the best balance'
      ' between Precision and Recall (F1-Score), making it the most reliable'
      ' for detecting network intrusions with minimal false alarms.'
  )
else:
  print(
      '⚠️ No results found! Please make sure you ran the evaluation cells for'
      ' your models first.'
  )

# Setup Best Model for Evaluation
if 'xgb_model' in globals():
  best_trained_model = xgb_model
  best_model_name = 'XGBoost'
  print('✅ Model assigned successfully.')
elif 'best_trained_model' in globals():
  print('✅ Model is ready in memory.')
else:
  print('⚠️ Warning: Model not found. Please run the training cell first.')

#ROC/PR Curves & Feature Importance (Self-Correcting)

from sklearn.metrics import auc, precision_recall_curve, roc_curve

if "best_trained_model" in locals() and hasattr(
    best_trained_model, "predict_proba"
):

  expected_features = getattr(
      best_trained_model, "n_features_in_", X_train.shape[1]
  )

  X_test_fixed = X_test.copy() if hasattr(X_test, "copy") else np.copy(X_test)

  if hasattr(X_test_fixed, "shape"):
    current_features = X_test_fixed.shape[1]
    if current_features < expected_features:
      pad_width = expected_features - current_features
      if isinstance(X_test_fixed, np.ndarray):
        X_test_fixed = np.pad(
            X_test_fixed,
            ((0, 0), (0, pad_width)),
            mode="constant",
            constant_values=0,
        )
      elif isinstance(X_test_fixed, pd.DataFrame):
        for i in range(pad_width):
          X_test_fixed[f"missing_feat_{i}"] = 0
    elif current_features > expected_features:
      if isinstance(X_test_fixed, np.ndarray):
        X_test_fixed = X_test_fixed[:, :expected_features]
      elif isinstance(X_test_fixed, pd.DataFrame):
        X_test_fixed = X_test_fixed.iloc[:, :expected_features]

  y_proba = best_trained_model.predict_proba(X_test_fixed)[:, 1]

  fpr, tpr, _ = roc_curve(y_test, y_proba)
  roc_auc = auc(fpr, tpr)

  plt.figure(figsize=(14, 5))

  plt.subplot(1, 2, 1)
  plt.plot(
      fpr,
      tpr,
      color="darkorange",
      lw=2,
      label=f"ROC curve (AUC = {roc_auc:.4f})",
  )
  plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
  plt.xlim([0.0, 1.0])
  plt.ylim([0.0, 1.05])
  plt.xlabel("False Positive Rate", fontsize=12)
  plt.ylabel("True Positive Rate", fontsize=12)
  plt.title(
      f"Receiver Operating Characteristic (ROC) - {best_model_name}",
      fontsize=14,
      fontweight="bold",
  )
  plt.legend(loc="lower right", fontsize=12)
  plt.grid(True, linestyle="--", alpha=0.5)

  precision, recall, _ = precision_recall_curve(y_test, y_proba)
  pr_auc = auc(recall, precision)

  plt.subplot(1, 2, 2)
  plt.plot(
      recall,
      precision,
      color="blue",
      lw=2,
      label=f"PR curve (AUC = {pr_auc:.4f})",
  )
  plt.xlabel("Recall", fontsize=12)
  plt.ylabel("Precision", fontsize=12)
  plt.title(
      f"Precision-Recall (PR) Curve - {best_model_name}",
      fontsize=14,
      fontweight="bold",
  )
  plt.legend(loc="lower left", fontsize=12)
  plt.grid(True, linestyle="--", alpha=0.5)

  plt.tight_layout()
  plt.show()

if "best_trained_model" in locals() and hasattr(
    best_trained_model, "feature_importances_"
):
  importances = best_trained_model.feature_importances_
  if hasattr(X_train, "columns") and len(X_train.columns) == len(importances):
    feature_names = X_train.columns
  else:
    feature_names = [f"Feature_{i}" for i in range(len(importances))]

  feature_imp_df = (
      pd.DataFrame({"Feature": feature_names, "Importance": importances})
      .sort_values(by="Importance", ascending=False)
      .head(10)
  )

  plt.figure(figsize=(10, 5))
  sns.barplot(
      data=feature_imp_df, x="Importance", y="Feature", palette="viridis"
  )
  plt.title(
      f"🔥 Top 10 Most Important Features - {best_model_name}",
      fontsize=14,
      fontweight="bold",
  )
  plt.xlabel("Importance Score", fontsize=12)
  plt.ylabel("Features", fontsize=12)
  plt.tight_layout()
  plt.show()
